export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
export const LOCATION = "LOCATION";
export const DESTINATIONlOCATION  = "DESTINATIONlOCATION"

export const LOADER = 'LOADER';